#-------------------------------
# Site Settings
title: Rezgar Muhammad
logo: # You can add own logo. For example '/images/logo.png'.
description: Rezgar is a software developer, who loves to share his knowledge and experience.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
#commented 
#    - title: 'Authors'
      #url: '/authors/'
    #- title: 'Videos'
      #url: '/videos/'
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Pages'
      submenu:
      - url: '/contact/'
        title: 'Contact'
      - url: '/elements/'
        title: 'Elements'


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Thoughts, code and others.
  hero__description: Personal space for my ideas, my work and learning journey.
  hero__image: '/images/RezgarMk.jpg' # You can add hero image. For example '/images/06.jpg'


#-------------------------------
# Author Global Settings
author:
  author__name: Rezgar Muhammad
  author__bio: I’m a published content creator, brand copywriter, photographer, and social media content creator and manager. I help brands connect with their customers by developing engaging content that entertains, educates, and offers value to their audience.
  author__avatar: /images/RezgarMk.jpg


#-------------------------------
# Blog Section Settings
blog__settings:
  enable: true
  blog__title: Latest Posts
  blog__description:


#-------------------------------
# Videos Section Settings
videos__settings:
  enable: false
  videos__title: Latest Videos
  videos__description:


#-------------------------------
# Tag Section Settings
tag__settings:
  enable: false
  tag: travel # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
author__section:
  enable: false
  author__section__title: Hello, my name is Alena. I’m reviewer and content creator.
  author__section__description: I’m a published content creator, brand copywriter, photographer, and social media content creator and manager. I help brands connect with their customers by developing engaging content that entertains, educates, and offers value to their audience.
  aurhor__section__button__text: More About Me
  aurhor__section__button__link: /about
  author__section__big__image: /images/100.jpg
  author__section__small__image: /images/101.jpg


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  enable: false
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address
  mailchimp__button__text: Subscribe
  mailchimp__background__image: /images/subscribe-bg.jpg


#-------------------------------
# Footer Settings
footer__description: you can reach me using different social accounts here


# Social Links
social:
- {icon: "twitter", link: "https://twitter.com/Rezgar_muhammad"}
- {icon: "codepen", link: "https://codepen.io"}
- {icon: "pinterest", link: "https://pinterest.com"}
- {icon: "vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


# Footer Navigation
footer__menu__settings:
  enable: false
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Elements'
      url: '/elements/'


#-------------------------------
# Contact Settings
contact:
  email: rezgar.muhammad@gmx.de # Add your form_id
  description:  # Add a description of your form

# NOTE
# Mria theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id